### ISSUE TITLE
Add legend to colormap on Hitmap

### ISSUE THREAD

**Issue by mtog** [1001genomes/AraGWAS#93]
Need to add legend. @timeu did you use quantiles? What would be the most appropriate legend?

**Comment by timeu** [comment]
The color bands are calculated using quantiles because the scores range from 5 - 116 and only a few very significant associations will lead to a non uniformily distributed coloring. However as a future extension we could implement a select box and allow the user to choose from different color methods (linear, quantiles, log, etc). The color legend is displayed below the hitmap
